pipeline {
    agent any 
    stages {
        stage(checkout){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/feature']],
                extensions: [], userRemoteConfigs: [[credentialsId: '475123b5-b026-4cf1-872f-ceec0be083ad', 
                url: 'https://github.com/pathipatireshma/Infra.git']]])
            }
        }
        stage('plan'){
            steps {
                withAWS(credentials: 'aws_credentials', region: 'us-east-1') {
                    sh """cd EC2/examples/
                            terraform init
                           terraform plan -var-file=infra.tfvars -out=planfile"""
                }
            }
        }
        stage('apply'){
            steps {
                withAWS(credentials: 'aws_credentials', region: 'us-east-1') {
                    if ($Terraform_Action == "apply") then {
                        sh """cd EC2/examples/
                              terraform apply planfile"""
                    } else if ($Terraform_Action == "destroy") {
                        sh "terraform destroy --auto-approve"
                    } else {
                        echo "Terraform_Action is required"
                    }   
                }
            }
        }
    }
}